### ISSUE TITLE
Can't access rbac url

### ISSUE THREAD

**Issue by hcharly** [bariew/yii2-rbac-cms-module#3]
Hi Bariew,
Thanks for this great RBAC module for Yii2.
Got it installed without problem and migrations did create needed tables.
But Trying to access it through "r=rbac/auth-item/index", I am getting an error:
Unable to resolve the request "rbac/auth-item/index".
Any Tips or hints?
Thanks

**Comment by bariew** [comment]
Hello! I have finally updated README file. Hope it will help - https://github.com/bariew/yii2-rbac-cms-module. 
In short, you need to define rbac module in config and apply module migrations.

**Comment by hcharly** [comment]
Yes, worked after updating config.
Many Thanks Bariew
